services:
  oracle:
    image: oracle/database:19.3.0-ee
    container_name: oracle
    networks:
      - optimize_data_insert_network
    ports:
      - "1522:1521"
    environment:
      - TZ=Asia/Seoul
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_DISABLE_ASYNCH_IO=true
      - ORACLE_SID=ORCL  # SID를 ORCL로 설정
    volumes:
#      - ./db/listener.ora:/opt/oracle/product/19.3.0/dbhome_1/network/admin/listener.ora
#      - ./db/init_listener.sql:/docker-entrypoint-initdb.d/init_listener.sql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/init_data.sql:/docker-entrypoint-initdb.d/init_data.sql


  redis:
    image: redis:latest
    container_name: redis-container
    networks:
      - optimize_data_insert_network
    restart: always
    ports:
      - "6379:6379"
    command: redis-server

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      - optimize_data_insert_network
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      - optimize_data_insert_network
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./provisioning/dashboards/my_dashboard.json:/etc/grafana/provisioning/dashboards/my_dashboard.json

  vm1:
    image: optimize-data-insert-vm1:1.0.0-SNAPSHOT
    networks:
      - optimize_data_insert_network
    ports:
      - "8181:8080"
    depends_on:
      - oracle
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@//oracle:1521/ORCL
      - SPRING_DATASOURCE_USERNAME=SYSTEM
      - SPRING_DATASOURCE_PASSWORD=oracle
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.OracleDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_DATASOURCE_HIKARI_MINIMUM-IDLE=5
      - SPRING_DATASOURCE_HIKARI_MAXIMUM-POOL-SIZE=50
      - SPRING_DATASOURCE_HIKARI_IDLE-TIMEOUT=60000
      - SPRING_DATASOURCE_HIKARI_MAX-LIFETIME=1800000
      - SPRING_DATASOURCE_HIKARI_POOL-NAME=SharedHikariPool
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - spring.application.vm-index=0
      - spring.application.total-vms=17

  vm2:
    image: optimize-data-insert-vm2:1.0.0-SNAPSHOT
    networks:
      - optimize_data_insert_network
    ports:
      - "8182:8080"
    depends_on:
      - oracle
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@//oracle:1521/ORCL
      - SPRING_DATASOURCE_USERNAME=SYSTEM
      - SPRING_DATASOURCE_PASSWORD=oracle
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.OracleDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_DATASOURCE_HIKARI_MINIMUM-IDLE=5
      - SPRING_DATASOURCE_HIKARI_MAXIMUM-POOL-SIZE=50
      - SPRING_DATASOURCE_HIKARI_IDLE-TIMEOUT=60000
      - SPRING_DATASOURCE_HIKARI_MAX-LIFETIME=1800000
      - SPRING_DATASOURCE_HIKARI_POOL-NAME=SharedHikariPool
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - spring.application.vm-index=1
      - spring.application.total-vms=17

  vm3:
    image: optimize-data-insert-vm3:1.0.0-SNAPSHOT
    networks:
      - optimize_data_insert_network
    ports:
      - "883:8080"
    depends_on:
      - oracle
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@//oracle:1521/ORCL
      - SPRING_DATASOURCE_USERNAME=SYSTEM
      - SPRING_DATASOURCE_PASSWORD=oracle
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.OracleDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_DATASOURCE_HIKARI_MINIMUM-IDLE=5
      - SPRING_DATASOURCE_HIKARI_MAXIMUM-POOL-SIZE=50
      - SPRING_DATASOURCE_HIKARI_IDLE-TIMEOUT=60000
      - SPRING_DATASOURCE_HIKARI_MAX-LIFETIME=1800000
      - SPRING_DATASOURCE_HIKARI_POOL-NAME=SharedHikariPool
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - spring.application.vm-index=2
      - spring.application.total-vms=17


  vm4:
    image: optimize-data-insert-vm4:1.0.0-SNAPSHOT
    networks:
      - optimize_data_insert_network
    ports:
      - "8184:8080"
    depends_on:
      - oracle
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@//oracle:1521/ORCL
      - SPRING_DATASOURCE_USERNAME=SYSTEM
      - SPRING_DATASOURCE_PASSWORD=oracle
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.OracleDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_DATASOURCE_HIKARI_MINIMUM-IDLE=5
      - SPRING_DATASOURCE_HIKARI_MAXIMUM-POOL-SIZE=50
      - SPRING_DATASOURCE_HIKARI_IDLE-TIMEOUT=60000
      - SPRING_DATASOURCE_HIKARI_MAX-LIFETIME=1800000
      - SPRING_DATASOURCE_HIKARI_POOL-NAME=SharedHikariPool
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - spring.application.vm-index=3
      - spring.application.total-vms=17

  vm5:
    image: optimize-data-insert-vm5:1.0.0-SNAPSHOT
    networks:
      - optimize_data_insert_network
    ports:
      - "8185:8080"
    depends_on:
      - oracle
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@//oracle:1521/ORCL
      - SPRING_DATASOURCE_USERNAME=SYSTEM
      - SPRING_DATASOURCE_PASSWORD=oracle
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.OracleDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_DATASOURCE_HIKARI_MINIMUM-IDLE=5
      - SPRING_DATASOURCE_HIKARI_MAXIMUM-POOL-SIZE=50
      - SPRING_DATASOURCE_HIKARI_IDLE-TIMEOUT=60000
      - SPRING_DATASOURCE_HIKARI_MAX-LIFETIME=1800000
      - SPRING_DATASOURCE_HIKARI_POOL-NAME=SharedHikariPool
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - spring.application.vm-index=4
      - spring.application.total-vms=17

  vm6:
    image: optimize-data-insert-vm6:1.0.0-SNAPSHOT
    networks:
      - optimize_data_insert_network
    ports:
      - "8186:8080"
    depends_on:
      - oracle
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@//oracle:1521/ORCL
      - SPRING_DATASOURCE_USERNAME=SYSTEM
      - SPRING_DATASOURCE_PASSWORD=oracle
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.OracleDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_DATASOURCE_HIKARI_MINIMUM-IDLE=5
      - SPRING_DATASOURCE_HIKARI_MAXIMUM-POOL-SIZE=50
      - SPRING_DATASOURCE_HIKARI_IDLE-TIMEOUT=60000
      - SPRING_DATASOURCE_HIKARI_MAX-LIFETIME=1800000
      - SPRING_DATASOURCE_HIKARI_POOL-NAME=SharedHikariPool
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - spring.application.vm-index=5
      - spring.application.total-vms=17

  vm7:
    image: optimize-data-insert-vm7:1.0.0-SNAPSHOT
    networks:
      - optimize_data_insert_network
    ports:
      - "8187:8080"
    depends_on:
      - oracle
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@//oracle:1521/ORCL
      - SPRING_DATASOURCE_USERNAME=SYSTEM
      - SPRING_DATASOURCE_PASSWORD=oracle
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.OracleDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_DATASOURCE_HIKARI_MINIMUM-IDLE=5
      - SPRING_DATASOURCE_HIKARI_MAXIMUM-POOL-SIZE=50
      - SPRING_DATASOURCE_HIKARI_IDLE-TIMEOUT=60000
      - SPRING_DATASOURCE_HIKARI_MAX-LIFETIME=1800000
      - SPRING_DATASOURCE_HIKARI_POOL-NAME=SharedHikariPool
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - spring.application.vm-index=6
      - spring.application.total-vms=17

  vm8:
    image: optimize-data-insert-vm8:1.0.0-SNAPSHOT
    networks:
      - optimize_data_insert_network
    ports:
      - "8188:8080"
    depends_on:
      - oracle
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@//oracle:1521/ORCL
      - SPRING_DATASOURCE_USERNAME=SYSTEM
      - SPRING_DATASOURCE_PASSWORD=oracle
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.OracleDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_DATASOURCE_HIKARI_MINIMUM-IDLE=5
      - SPRING_DATASOURCE_HIKARI_MAXIMUM-POOL-SIZE=50
      - SPRING_DATASOURCE_HIKARI_IDLE-TIMEOUT=60000
      - SPRING_DATASOURCE_HIKARI_MAX-LIFETIME=1800000
      - SPRING_DATASOURCE_HIKARI_POOL-NAME=SharedHikariPool
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - spring.application.vm-index=7
      - spring.application.total-vms=17

  vm9:
    image: optimize-data-insert-vm9:1.0.0-SNAPSHOT
    networks:
      - optimize_data_insert_network
    ports:
      - "8189:8080"
    depends_on:
      - oracle
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@//oracle:1521/ORCL
      - SPRING_DATASOURCE_USERNAME=SYSTEM
      - SPRING_DATASOURCE_PASSWORD=oracle
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.OracleDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_DATASOURCE_HIKARI_MINIMUM-IDLE=5
      - SPRING_DATASOURCE_HIKARI_MAXIMUM-POOL-SIZE=50
      - SPRING_DATASOURCE_HIKARI_IDLE-TIMEOUT=60000
      - SPRING_DATASOURCE_HIKARI_MAX-LIFETIME=1800000
      - SPRING_DATASOURCE_HIKARI_POOL-NAME=SharedHikariPool
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - spring.application.vm-index=8
      - spring.application.total-vms=17

  vm10:
    image: optimize-data-insert-vm10:1.0.0-SNAPSHOT
    networks:
      - optimize_data_insert_network
    ports:
      - "8190:8080"
    depends_on:
      - oracle
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@//oracle:1521/ORCL
      - SPRING_DATASOURCE_USERNAME=SYSTEM
      - SPRING_DATASOURCE_PASSWORD=oracle
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.OracleDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_DATASOURCE_HIKARI_MINIMUM-IDLE=5
      - SPRING_DATASOURCE_HIKARI_MAXIMUM-POOL-SIZE=50
      - SPRING_DATASOURCE_HIKARI_IDLE-TIMEOUT=60000
      - SPRING_DATASOURCE_HIKARI_MAX-LIFETIME=1800000
      - SPRING_DATASOURCE_HIKARI_POOL-NAME=SharedHikariPool
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - spring.application.vm-index=9
      - spring.application.total-vms=17

networks:
  optimize_data_insert_network:
    driver: bridge