spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//oracle:1521/ORCL
    username: SYSTEM
    password: oracle
    hikari:
      minimum-idle: 10        # 최소 유휴 커넥션 수
      maximum-pool-size: 200   # 최대 커넥션 풀 크기
      idle-timeout: 300000    # 커넥션 유휴 타임아웃
      connection-timeout: 60000  # 최대 커넥션 대기 시간
      max-lifetime: 1800000   # 커넥션 최대 생명 주기
      pool-name: MyHikariPool # 풀 이름
      register-mbeans: true

  properties:
    hibernate:
      jdbc:
        batch_size: 5000

#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#    open-in-view: false
#    properties:
#      hibernate:
#        format_sql: true
#        dialect: org.hibernate.dialect.OracleDialect
#        order_inserts: true
#        order_updates: true
#        jdbc:
#          batch_size: 20000     # 배치 사이즈 지정
