-- USERS 테이블스페이스가 존재하지 않으면 생성
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLESPACE USERS DATAFILE ''/opt/oracle/oradata/ORCL/users01.dbf'' SIZE 100M AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN -- ORA-00955: name is already used by an existing object
            RAISE;
        END IF;
END;
/

-- SYSTEM 계정의 기본 테이블스페이스 변경
ALTER USER SYSTEM DEFAULT TABLESPACE USERS;

CREATE TABLE TB_DTF_HRAS_AUTO (
      CS_ID VARCHAR2(100) NOT NULL,
      PDCT_DT TIMESTAMP NOT NULL,
      PROJECT_ID NUMBER NOT NULL,
      NAME VARCHAR2(30) NOT NULL,
      RIVER_NAME VARCHAR2(30) NOT NULL,
      RIVER_REACH VARCHAR2(30) NOT NULL,
      RIVER_CODE NUMBER NOT NULL,
      WTLV_VAL NUMBER NOT NULL,
      FLOW_VAL NUMBER NOT NULL,
      VEL_VAL NUMBER NOT NULL,
      CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      PRIMARY KEY (CS_ID, PDCT_DT)
);

-- [ver9] 테스트용 인덱스 생성: 함수 기반 인덱스를 따로 생성
CREATE INDEX IDX_TB_DTF_HRAS_AUTO_FUNC_CS_ID ON TB_DTF_HRAS_AUTO(TO_NUMBER(SUBSTR(cs_id, 4)));


-- PARTITION BY RANGE (CREATED_DATE)
-- INTERVAL (NUMTODSINTERVAL(1, 'MINUTE')) -- 매분 새로운 파티션 생성
-- (
--     PARTITION p_initial VALUES LESS THAN (TO_DATE('2023-01-01', 'YYYY-MM-DD'))
-- )
-- TABLESPACE USERS
-- ENABLE ROW MOVEMENT;